kind = "mobile"
previewPath = "/"
title = "StreamTV"
version = "1.0.0"
id = "artifacts/iptv-tv"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19231

[services.development]
run = "pnpm --filter @workspace/iptv-tv run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/iptv-tv", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/iptv-tv", "run", "serve" ]

[services.env]
PORT = "19231"
BASE_PATH = "/"
